### ISSUE TITLE
How Specify a custom directory (not well knows) to create a file

### ISSUE THREAD

**Issue by Gildissimo** [KristofferStrube/Blazor.FileAPI#1]
var options = new SaveFilePickerOptionsStartInWellKnownDirectory() { SuggestedName = "PROVA.D01", StartIn = "C:\test\"};
FileHandle = await FileSystemAccessService.ShowSaveFilePickerAsync(options);

**Comment by KristofferStrube** [comment]
This isn't related to this library but I see that also found the right repository so I a closing this.
